# Generated by Django 5.0.2 on 2024-03-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
