# Generated by Django 5.0.2 on 2024-03-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_transaction_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transfer',
        ),
    ]
