# Generated by Django 5.0.2 on 2024-03-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payapp.request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_sent', 'Payment Sent'), ('request_sent', 'Request Sent'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined')], default='payment_sent', max_length=20),
        ),
    ]
